### ISSUE TITLE
panic: sync: WaitGroup is reused before previous Wait has returned

### ISSUE THREAD

**Issue by gadolf66** [network-quality/server#21]
Hello!
FIrst of all, thanks for working on a better Internet.
I'm doing some rough tests and got this error on the client side:

```
gustavo@ubuntu:~/goresponsiveness$ ./networkQuality --config networkquality.nosotros.ong.br --port 4043
08-31-2022 19:05:05 UTC Go Responsiveness to networkquality.nosotros.ong.br:4043...
Download:   4.184 Mbps (  0.523 MBps), using 12 parallel connections.
Upload:    34.293 Mbps (  4.287 MBps), using 28 parallel connections.
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 1535 [running]:
sync.(*WaitGroup).Wait(0xc0000397d0?)
	/usr/local/go/src/sync/waitgroup.go:138 +0x85
github.com/network-quality/goresponsiveness/rpm.ForeignProber.func1.1()
	/home/gustavo/goresponsiveness/rpm/rpm.go:290 +0x1d
github.com/network-quality/goresponsiveness/utilities.OrTimeout.func1.1()
	/home/gustavo/goresponsiveness/utilities/utilities.go:167 +0x5b
created by github.com/network-quality/goresponsiveness/utilities.OrTimeout.func1
	/home/gustavo/goresponsiveness/utilities/utilities.go:161 +0x85

```
On the server side, I have this:

```
gustavo@srv2:~/server/go$ ./networkqualityd  --cert-file fullchain.pem --key-file privkey.pem --public-name networkquality.nosotros.ong.br --listen-addr 0.0.0.0
2022/08/31 16:04:48 Network Quality URL: https://networkquality.example.com:4043/config
2022/08/31 16:04:59 http: TLS handshake error from 198.199.98.246:59986: EOF
2022/08/31 16:05:16 Error writing content of length 4294967296: client disconnected
2022/08/31 16:05:16 Error writing content of length 4294967296: client disconnected
2022/08/31 16:05:16 Error writing content of length 4294967296: write tcp 192.168.1.5:4043->177.38.98.213:50925: write: connection reset by peer
2022/08/31 16:05:16 Error writing content of length 4294967296: write tcp 192.168.1.5:4043->177.38.98.213:6981: write: connection reset by peer
2022/08/31 16:05:16 Error writing content of length 4294967296: client disconnected
2022/08/31 16:05:16 Error writing content of length 4294967296: client disconnected
2022/08/31 16:05:16 Error writing content of length 4294967296: client disconnected
2022/08/31 16:05:16 Error writing content of length 4294967296: client disconnected
2022/08/31 16:05:16 Error writing content of length 4294967296: client disconnected
2022/08/31 16:05:16 Error writing content of length 4294967296: client disconnected
2022/08/31 16:05:16 Error writing content of length 4294967296: client disconnected
2022/08/31 16:05:16 Error writing content of length 4294967296: write tcp 192.168.1.5:4043->177.38.98.213:48967: write: connection reset by peer

```
What am I missing?

**Comment by gadolf66** [comment]
Sorry, but things look better (at least on the client side) on a second and third run:

```
gustavo@ubuntu:~/goresponsiveness$ ./networkQuality --config networkquality.nosotros.ong.br --port 4043
08-31-2022 19:27:44 UTC Go Responsiveness to networkquality.nosotros.ong.br:4043...
Download:   1.718 Mbps (  0.215 MBps), using 12 parallel connections.
Upload:    35.451 Mbps (  4.431 MBps), using 32 parallel connections.
RPM:   631
gustavo@ubuntu:~/goresponsiveness$ ./networkQuality --config networkquality.nosotros.ong.br --port 4043
08-31-2022 19:28:08 UTC Go Responsiveness to networkquality.nosotros.ong.br:4043...
Download:   3.343 Mbps (  0.418 MBps), using 12 parallel connections.
Upload:    34.088 Mbps (  4.261 MBps), using 32 parallel connections.
RPM:   777
```

The server looks like this:
```

2022/08/31 16:27:58 Error writing content of length 4294967296: client disconnected
2022/08/31 16:27:58 Error writing content of length 4294967296: client disconnected
2022/08/31 16:27:58 Error writing content of length 4294967296: client disconnected
2022/08/31 16:27:58 Error writing content of length 4294967296: write tcp 192.168.1.5:4043->177.38.98.213:27796: write: broken pipe
2022/08/31 16:27:58 Error writing content of length 4294967296: client disconnected
2022/08/31 16:27:58 Error writing content of length 4294967296: client disconnected
2022/08/31 16:27:58 Error writing content of length 4294967296: client disconnected
2022/08/31 16:27:58 Error writing content of length 4294967296: client disconnected
2022/08/31 16:27:58 Error writing content of length 4294967296: write tcp 192.168.1.5:4043->177.38.98.213:16909: write: broken pipe
2022/08/31 16:27:58 Error writing content of length 4294967296: client disconnected
2022/08/31 16:27:58 Error writing content of length 4294967296: client disconnected
2022/08/31 16:27:58 Error writing content of length 4294967296: write tcp 192.168.1.5:4043->177.38.98.213:28411: write: broken pipe
2022/08/31 16:28:22 Error writing content of length 4294967296: client disconnected
2022/08/31 16:28:22 Error writing content of length 4294967296: client disconnected
2022/08/31 16:28:22 Error writing content of length 4294967296: client disconnected
2022/08/31 16:28:22 Error writing content of length 4294967296: client disconnected
2022/08/31 16:28:22 Error writing content of length 4294967296: client disconnected
2022/08/31 16:28:22 Error writing content of length 4294967296: write tcp 192.168.1.5:4043->177.38.98.213:47917: write: connection reset by peer
2022/08/31 16:28:22 Error writing content of length 4294967296: write tcp 192.168.1.5:4043->177.38.98.213:40514: write: connection reset by peer
2022/08/31 16:28:22 Error writing content of length 4294967296: write tcp 192.168.1.5:4043->177.38.98.213:53515: write: connection reset by peer
2022/08/31 16:28:22 Error writing content of length 4294967296: write tcp 192.168.1.5:4043->177.38.98.213:54090: write: connection reset by peer
2022/08/31 16:28:22 Error writing content of length 4294967296: client disconnected
2022/08/31 16:28:22 Error writing content of length 4294967296: write tcp 192.168.1.5:4043->177.38.98.213:5239: write: connection reset by peer
2022/08/31 16:28:22 Error writing content of length 4294967296: client disconnected
```
Anything to worry about or is it working as expected?

**Comment by randall** [comment]
Sorry, the wait group thing is definitely a bug. And those logs can be ignored. #23 will fix the WaitGroup issue and has some silencing of those types of "errors".
